### ISSUE TITLE
存证列表问题

### ISSUE THREAD

**Issue by Jandiasnow** [bestchains/bc-saas#29]
1.存证名称搜不到数据
![image](https://github.com/bestchains/bc-saas/assets/19659148/840cdd16-a216-441b-a05e-5626b518119d)
2. 存证时间搜索500
![image](https://github.com/bestchains/bc-saas/assets/19659148/9c89de24-1b34-488a-8a3b-79d9b865349d)
3.缺少存证状态字段
4.缺少下载证书接口

**Comment by 0xff-dev** [comment]
2. 时间搜索问题
```sql
alter table "proof-c0zpw_depository_depository" alter column "trustedTimestamp" type bigint USING "trustedTimestamp"::bigint;
```

**Comment by 0xff-dev** [comment]
@bjwswang 3, 4 两个问题是不是不需要处理。

**Comment by bjwswang** [comment]
> @bjwswang 3, 4 两个问题是不是不需要处理。

不需要处理。
