### ISSUE TITLE
存证详情问题

### ISSUE THREAD

**Issue by Jandiasnow** [bestchains/bc-saas#30]
![62e5bc4dfb788872e8c8b9c4f1465315](https://github.com/bestchains/bc-saas/assets/19659148/0c66de5e-796e-46ef-9cb4-2db26641bf88)
1. 缺少图片中标红对应字段
2. 缺少下载证书接口
3. 缺少文件预览接口

**Comment by bjwswang** [comment]
@Jandiasnow 

- 存证主体，固定填写为`个人`
- 身份证，暂时没有身份认证，这个字段先去掉
-文件类型： contentType
- 文件备注: description
- 存证状态去掉
- 存证hash:   kid
- 文件哈希: contentID
